'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.42.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://schemas.microsoft.com/office/infopath/2003/myXSD/2007-01-21T17:56:39", IsNullable:=false)>  _
Partial Public Class Loan
    
    Private sSNField As String
    
    Private firstNameField As String
    
    Private lastNameField As String
    
    Private streetField As String
    
    Private cityField As String
    
    Private stateField As String
    
    Private zipField As String
    
    Private incomeField As System.Nullable(Of Double)
    
    Private incomeFieldSpecified As Boolean
    
    Private loanAmtField As System.Nullable(Of Double)
    
    Private loanAmtFieldSpecified As Boolean
    
    Private myFieldsField As myFields
    
    Private anyAttrField() As System.Xml.XmlAttribute
    
    '''<remarks/>
    Public Property SSN() As String
        Get
            Return Me.sSNField
        End Get
        Set
            Me.sSNField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property FirstName() As String
        Get
            Return Me.firstNameField
        End Get
        Set
            Me.firstNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property LastName() As String
        Get
            Return Me.lastNameField
        End Get
        Set
            Me.lastNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Street() As String
        Get
            Return Me.streetField
        End Get
        Set
            Me.streetField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property City() As String
        Get
            Return Me.cityField
        End Get
        Set
            Me.cityField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property State() As String
        Get
            Return Me.stateField
        End Get
        Set
            Me.stateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Zip() As String
        Get
            Return Me.zipField
        End Get
        Set
            Me.zipField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property Income() As System.Nullable(Of Double)
        Get
            Return Me.incomeField
        End Get
        Set
            Me.incomeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property IncomeSpecified() As Boolean
        Get
            Return Me.incomeFieldSpecified
        End Get
        Set
            Me.incomeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property LoanAmt() As System.Nullable(Of Double)
        Get
            Return Me.loanAmtField
        End Get
        Set
            Me.loanAmtField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property LoanAmtSpecified() As Boolean
        Get
            Return Me.loanAmtFieldSpecified
        End Get
        Set
            Me.loanAmtFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property myFields() As myFields
        Get
            Return Me.myFieldsField
        End Get
        Set
            Me.myFieldsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
    Public Property AnyAttr() As System.Xml.XmlAttribute()
        Get
            Return Me.anyAttrField
        End Get
        Set
            Me.anyAttrField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://schemas.microsoft.com/office/infopath/2003/myXSD/2007-01-21T17:56:39", IsNullable:=false)>  _
Partial Public Class myFields
End Class
